controller_manager:
  ros__parameters:
    update_rate: 1000

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    pose_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_impedance_controller:
      type: crisp_controllers/CartesianController

    cartesian_impedance_controller:
      type: crisp_controllers/CartesianController

    gravity_compensation:
      type: joint_trajectory_controller/JointTrajectoryController

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: false

pose_broadcaster:
  ros__parameters:
    use_sim_time: false

joint_trajectory_controller:
  ros__parameters:
    use_sim_time: false
    joints:
      - fr3_joint1
      - fr3_joint2
      - fr3_joint3
      - fr3_joint4
      - fr3_joint5
      - fr3_joint6
      - fr3_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

joint_impedance_controller:
    ros__parameters:
      joints:
        - fr3_joint1
        - fr3_joint2
        - fr3_joint3
        - fr3_joint4
        - fr3_joint5
        - fr3_joint6
        - fr3_joint7

      end_effector_frame: fr3_link8
      base_frame: base

      task:
        k_pos_x: 0.0
        k_pos_y: 0.0
        k_pos_z: 0.0
        k_rot_x: 0.0
        k_rot_y: 0.0
        k_rot_z: 0.0

      max_delta_tau: 0.5

      nullspace: 
        stiffness: 5.0
        projector_type: none  # So we are directly controlling the joints!
        damping: 0.5
        max_tau: 5.0
        regularization: 1.0e-06
        weights:
          fr3_joint1.value: 150.0
          fr3_joint2.value: 150.0
          fr3_joint3.value: 150.0
          fr3_joint4.value: 150.0
          fr3_joint5.value: 50.0
          fr3_joint6.value: 30.0
          fr3_joint7.value: 10.0

      use_friction: true
      use_coriolis_compensation: true
      use_local_jacobian: true
      limit_error: true
      limit_torques: true


cartesian_impedance_controller:
    ros__parameters:
      joints:
        - fr3_joint1
        - fr3_joint2
        - fr3_joint3
        - fr3_joint4
        - fr3_joint5
        - fr3_joint6
        - fr3_joint7

      end_effector_frame: fr3_hand_tcp
      base_frame: base

      filter:
        q: 0.5
        dq: 0.5
        output_torque: 0.5

      task:
        k_pos_x: 300.0
        k_pos_y: 300.0
        k_pos_z: 300.0
        k_rot_x: 30.0
        k_rot_y: 30.0
        k_rot_z: 30.0

      nullspace: 
        stiffness: 5.0

      # log:
      #   enabled: true
      #   timing: true

      limit_error: true
      limit_torques: true
      use_friction: true
      use_coriolis_compensation: true
      use_local_jacobian: true
      variable_stiffness:
        enabled: true
    


gravity_compensation:
  ros__parameters:
    use_sim_time: false
    joints:
      - fr3_joint1
      - fr3_joint2
      - fr3_joint3
      - fr3_joint4
      - fr3_joint5
      - fr3_joint6
      - fr3_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
